Updated time out

diff --git a/.github/workflows/trigger-jenkins.yml b/.github/workflows/trigger-jenkins.yml
--- a/.github/workflows/trigger-jenkins.yml
+++ b/.github/workflows/trigger-jenkins.yml
@@ -31,31 +31,44 @@ jobs:
           echo "Latest Build : $LATEST_BUILD"
           echo "Latest Build URL : $LATEST_BUILD_URL"
           echo "build_url=$LATEST_BUILD_URL" >> $GITHUB_OUTPUT
-        
             
 
       - name: Wait for Jenkins job to complete
         run: |
           echo "Waiting for Jenkins job to complete..."
+          MAX_ATTEMPTS=10
+          SLEEP_SECONDS=5
+          COUNTER=0
           
-          BUILD_INFO=$(curl -s -u ${JENKINS_USERNAME}:${JENKINS_TOKEN} \
+          while true; do
+            BUILD_INFO=$(curl -s -u ${JENKINS_USERNAME}:${JENKINS_TOKEN} \
             "${{ steps.trigger.outputs.build_url }}api/json")
 
-          echo "Build Info : $BUILD_INFO"
-
-          BUILDING=$(python3 -c "import sys, json; print(json.loads(sys.argv[1])['building'])" "$BUILD_INFO")
-          RESULT=$(python3 -c "import sys, json; print(json.loads(sys.argv[1])['result'])" "$BUILD_INFO")
-
-          echo "Building : $BUILDING"
-          echo "Build Result : $RESULT"
-          do
-            if [[ "$BUILDING" == "false" ]]; then
-              echo "Build finished with result: $RESULT"
-              echo "result=$RESULT" >> $GITHUB_OUTPUT
+            echo "Build Info : $BUILD_INFO"
+            STATUS=$(python3 -c "import sys, json; print(json.loads(sys.argv[1])['result'])" "$BUILD_INFO")
+          
+            if [[ "$STATUS" == "SUCCESS" ]]; then
+              echo "Jenkins build succeeded!"
               break
+            elif [[ "$STATUS" == "FAILURE" ]]; then
+              echo "Jenkins build failed!"
+              exit 1
+            elif [[ "$STATUS" == "ABORTED" ]]; then
+              echo "Jenkins build aborted!"
+              exit 1
+            elif [[ "$STATUS" == "null" ]]; then
+              echo "Build still running..."
+            else
+              echo "Unknown status: $STATUS"
             fi
-              echo "Still building..."
-            sleep 5
+          
+            COUNTER=$((COUNTER+1))
+            if [[ $COUNTER -ge $MAX_ATTEMPTS ]]; then
+              echo "Timed out waiting for Jenkins build."
+              exit 1
+            fi
+          
+            sleep $SLEEP_SECONDS
           done
 
       - name: Notify GitHub PR (optional)
